import type { Content } from './types';

export const contentEn: Content = {
  event: {
    date: 'March 28, 2026',
    time: '2:00 PM - 6:00 PM',
    venue: 'University of Ottawa',
    ctaSubtext: 'Limited number of attendees • Early registration recommended',
  },
  links: {
    registration: 'https://luma.com/aoycaats',
    email: 'fabdo006@uottawa.ca',
    speakerApplication: 'https://forms.gle/sDqad7jwHUjBpk5KA',
    newsletterFormEndpoint: 'https://formspree.io/f/xdadvrog',
    instagram: {
      url: 'https://www.instagram.com/cegsc.ieee.uottawa/',
      handle: '@cegsc.ieee.uottawa',
    },
    linkedin: {
      url: 'https://www.linkedin.com/in/cegsc-ieee-uottawa-25879139b/',
      handle: 'CEGSC.IEEE. UOTTAWA',
    },
  },
  hero: {
    tagline: "Spring 2026 • Registration Open",
    title: {
      line1: 'Computer',
      line2: 'Engineering',
      line3: 'Conference',
    },
    subtitle: "For engineers who know what they do, but not who they are.\nReal stories. Real Impact.",
  },
  speakers: [
    {
      name: 'Wassim El Ahmar',
      role: 'Machine learning and computer vision',
      talkTitle: 'On an Engineer\'s Future in the era of AI',
      preview: 'Professor at the University of Ottawa teaching programming to software engineering. PhD in electrical and computer engineering, research at CVPR and ECCV.',
      detailType: 'quote',
      detailText: 'I serve as a professor at the University of Ottawa in a long-term appointment (LTA), teaching courses ranging from programming and data structures to software engineering and interaction design. I have presented my academic research at top venues, such as CVPR and ECCV, advancing thermal-RGB sensor fusion, object detection and thermal multiple object tracking. I hold a PhD in electrical and computer engineering from the University of Ottawa, where my doctoral work focused on thermal-RGB sensory data for robust perception. I am also a licensed professional engineer (PEng) in Ontario.',
      attribution: 'Wassim El Ahmar',
      linkedin: 'https://www.linkedin.com/in/wassimea/',
      anchorId: 'speaker-wassim',
      image: '/speakers/wassim-el-ahmar.jpeg',
    },
    {
      name: 'Peter Oliha',
      role: 'Lead Backend Engineer | SaaS Founder • APIs & Cloud',
      talkTitle: 'From Optimization to Choice',
      preview: 'Software engineer based in Ottawa. 20 years of code, 15 professionally. Builds backend systems and a portfolio of products.',
      detailType: 'quote',
      detailText: 'I\'m a software engineer based in Ottawa, Canada. I\'ve been writing code for 20 years, 15 of those professionally. By day, I build backend systems and APIs. On the side, I\'m building a portfolio of products: Jobven, MapleStack, FindChildcare, and KidzLog. Most of what I know came from shipping my own projects.',
      attribution: 'Peter Oliha',
      linkedin: 'https://www.linkedin.com/in/peter-o-oliha-93b27118b/',
      anchorId: 'speaker-peter',
      image: '/speakers/peter-oliha.png',
    },
    {
      name: 'Jude Bennett',
      role: 'Software development',
      talkTitle: 'On coding the skies',
      preview: 'Recent Waterloo computer engineering grad, now software developer at NAV CANADA. Journey from undergrad to keeping Canadian air traffic moving.',
      detailType: 'quote',
      detailText: 'I\'m a recent graduate from the University of Waterloo\'s computer engineering program, and I currently work as a software developer for NAV CANADA here in Ottawa. My talk focuses on my journey from engineering undergraduate to full-time professional at one of the most important and least known companies in the country. When was the last time you flew on a plane? Did you think about who helps make sure it takes off, lands, and crosses the country without the sky turning into a giant scheduling disaster? Probably not. Most people do not. But behind every flight is a massive system of coordination, control, and technology that keeps Canadian air traffic moving safely and efficiently. One of the key organizations behind that system is NAV CANADA, one of the least talked about but most important companies in the country. Through my perspective, you\'ll get a look inside that world and what it\'s like to work at a company that keeps the. whole. country. moving.',
      attribution: 'Jude Bennett',
      anchorId: 'speaker-jude',
      image: '/speakers/jude-bennett.jpg',
    },
    {
      name: 'Yousef Rafique',
      role: 'Consulting Engineering - Automation & AI',
      talkTitle: 'On building with Intention: Who Are We Really Building For?',
      preview: 'Computer engineer across startups, research, and PhD work. Now supports automation and AI in large network systems.',
      detailType: 'quote',
      detailText: 'I\'m a computer engineer who has moved across different parts of the field. I started by building a startup, then went into research and began a PhD focused on optimizing distributed cloud and IoT systems. I\'ve worked in R&D environments delivering new features, and today I work closer to customers, supporting automation and AI solutions in large network systems.',
      attribution: 'Yousef Rafique',
      linkedin: 'https://www.linkedin.com/in/yousefrafique/',
      anchorId: 'speaker-yousef',
      image: '/speakers/yousef-rafique.png',
    },
    {
      name: 'Alfredo Herrera',
      role: 'Consultant on digital integrated circuit',
      talkTitle: 'On The Accidental verifier',
      preview: 'Consultant on ASIC/FPGA verification. 30+ years at Nortel, Ericsson, IBM, Ciena, Xilinx, AMD, and more.',
      detailType: 'quote',
      detailText: 'I\'m a consultant on digital integrated circuit (ASIC, FPGA) verification and design. I have over 30 years of experience that includes work at Nortel, Ericsson, IBM, Ciena, Xilinx, AMD, ASML, MDA as well as some startups (Promatory, Axiado) and medium sized companies (Memotec, Dataradio). I have also volunteered for the IEEE and OIQ, coached house league baseball and soccer, and served as a councillor at summer camp. I live in Ottawa with my wife and three daughters.',
      attribution: 'Alfredo Herrera',
      linkedin: 'https://www.linkedin.com/in/alfredoherreraeng/',
      anchorId: 'speaker-alfredo',
      image: '/speakers/alfredo-herrera.jpeg',
    },
    {
      name: 'Matthew Jerabek',
      role: 'Managing Innovation & Entrepreneurship',
      talkTitle: 'On FAILURE',
      preview: 'Maker at heart. Leads makerspace at Oakland College. 10+ years in marketing, built and failed at many things along the way.',
      detailType: 'quote',
      detailText: 'I\'m a maker at heart. I make physical things and digital things. I love to see where art and code can intersect, and I love novel ideas. I\'ve led a makerspace and opened it at Oakland College since 2018. I\'ve also been a marketing manager for many years with over 10 years of experience, and I\'ve built, tried, and failed at many different things along the way.',
      attribution: 'Matthew Jerabek',
      linkedin: 'https://www.linkedin.com/in/matthewjerabek/',
      anchorId: 'speaker-jerabek',
      image: '/speakers/matthew-jerabek.png',
    },
    {
      name: 'Stephen Gagné',
      role: 'Helping student entrepreneurs turn bold ideas into awesome outcomes.',
      talkTitle: 'Writing Code Is the Last Thing You Should Do',
      preview: 'First coded at age six in 1993. Pivoted through social sciences and business. Now helps aspiring entrepreneurs at Algonquin College.',
      detailType: 'quote',
      detailText: 'I first discovered programming in 1993, at the age of six years old, when I took out a book of code from my local library. Although all I had at my disposal was a Q BASIC editor I had to launch from DOS, I was instantly hooked by what seemed like magic. I could type weird looking words into an editor, hit \'Run\' and see the computer come to life. In the 3 decades since that first experience, my relationship with programming hasn\'t been as consistent as I might like. A serious allergy to Integral Calculus cut short my dreams of being an engineer, and I took an educational detour into Social Sciences before pivoting completely into business. At 30, after realizing that my path wasn\'t leading me where I wanted to be, I went back to school to study Interactive Media Design. Coding came pretty naturally back to me, but it was completely different now. It no longer mattered how few lines I could do something in or how many milliseconds I could shave off the compute time. Instead, I had to learn to think about what my user wanted and how code might deliver that. Now, almost 33 years after I wrote my first ever lines of code, I work with dozens of aspiring tech entrepreneurs each year at Algonquin College, helping them learn to see code as a tool they can use to help their customers.',
      attribution: 'Stephen Gagné',
      linkedin: 'https://www.linkedin.com/in/stephengagne/',
      anchorId: 'speaker-stephen',
      image: '/speakers/stephen-gagne.png',
    },
    {
      name: 'Dan Cooper',
      role: 'Chief IT Architect, Government of Canada',
      talkTitle: 'On architecting government-scale systems and what it means to build technology at national scale',
      preview: 'Chief IT Architect in the Office of the CIO of Canada. Designs technology at the scale of national systems.',
      detailType: 'description',
      detailText: 'Dan Cooper serves as Chief IT Architect in the Office of the Chief Information Officer of Canada. His work offers a view into what it means to design and think about technology at the scale of national systems and public infrastructure.',
      linkedin: 'https://www.linkedin.com/in/thedancooper/',
      anchorId: 'speaker-dan',
      image: '/speakers/dan-cooper.png',
    },
  ],
  schedule: {
    sectionLabel: 'SCHEDULE',
    title: 'Event Flow',
    intro: 'Three curated blocks of stories, lessons, and engineering perspectives — designed to move from foundations, to reflection, to larger-scale impact.',
    note: 'Speaker details and full bios can be found in the Speakers section.',
    blocks: [
      {
        blockLabel: 'BLOCK 01',
        blockTitle: 'Foundations & First Principles',
        type: 'speakers',
        items: [
          { name: 'Stephen Gagné', title: 'Writing Code Is the Last Thing You Should Do', href: '#speaker-stephen' },
          { name: 'Alfredo Herrera', title: 'On The Accidental verifier', href: '#speaker-alfredo' },
          { name: 'Jude Bennett', title: 'On coding the skies', href: '#speaker-jude' },
          { name: 'Wassim El Ahmar', title: 'On an Engineer\'s Future in the era of AI', href: '#speaker-wassim' },
        ],
      },
      {
        blockLabel: 'INTERMISSION 01',
        blockTitle: 'Short Intermission',
        type: 'intermission',
      },
      {
        blockLabel: 'BLOCK 02',
        blockTitle: 'Reflection & Perspective',
        type: 'speakers',
        items: [
          { name: 'Matt Lemay', title: 'The Engineer\'s Edge: Building Reliable AI Through Standards and Architecture' },
          { name: 'Peter Oliha', title: 'From Optimization to Choice', href: '#speaker-peter' },
          { name: 'Michel de Léséleuc', title: 'From Lab to Leadership: 40 Years in RF' },
        ],
      },
      {
        blockLabel: 'INTERMISSION 02',
        blockTitle: 'Long Intermission',
        type: 'intermission',
      },
      {
        blockLabel: 'BLOCK 03',
        blockTitle: 'Scale & Impact',
        type: 'speakers',
        items: [
          { name: 'Yousef Rafique', title: 'On building with Intention: Who Are We Really Building For?', href: '#speaker-yousef' },
          { name: 'Matthew Jerabek', title: 'On FAILURE', href: '#speaker-jerabek' },
          { name: 'Dan Cooper', title: 'On architecting government-scale systems', href: '#speaker-dan' },
        ],
      },
      {
        blockLabel: 'INTERMISSION 03',
        blockTitle: 'Dinner and networking',
        type: 'intermission',
      },
    ],
  },
  team: [
    { name: 'Mariia Yermolenko', role: 'Lead Organizer', image: '/team/mariia.jpg' },
    { name: 'Fatimata Abdou Dramane', role: 'Program Director', image: '/team/fatima.jpg' },
    { name: 'Asif Rahman', role: 'Logistics Lead', image: '/team/asif.jpg' },
    { name: 'Paul Chukwu', role: 'Sponsorship Lead', image: '/team/paul.jpg' },
    { name: 'Basma Ben Taleb', role: 'Marketing Lead', image: '/team/basma.jpg' },
    { name: 'Dounia Bouimajdil', role: 'Operations & Experience Lead', image: '/team/Dounia.jpg' },
  ],
  faqs: [
    {
      question: 'Where will the event take place?',
      answer: 'The event will be held at uOttawa. The exact venue will be shared once finalized.',
    },
    {
      question: 'When will the schedule be released?',
      answer: "We'll share the full schedule closer to the event, once speakers are confirmed and details are locked in.",
    },
    {
      question: 'Who is this event for?',
      answer: "Anyone in tech or engineering who has ever felt unsure about their path, questioned where they're going, or wanted a clearer sense of what building things actually means. Students, recent grads, and professionals are all welcome.",
    },
    {
      question: 'Can I participate as a speaker or volunteer?',
      answer: "Yes. We are still welcoming speaker proposals and volunteers. More information is available on the site, and you're welcome to reach out if you're unsure where you fit.",
    },
    {
      question: 'Will food be provided?',
      answer: "Yes. We're planning shared food during the event and will share details closer to the date.",
    },
    {
      question: 'What should I bring?',
      answer: 'Just yourself and an open mind. No preparation required.',
    },
  ],
  ui: {
    nav: {
      schedule: 'Schedule',
      about: 'About',
      speakers: 'Speakers',
      event: 'Event',
      team: 'Team',
      contact: 'Contact',
      attend: 'Attend',
    },
    hero: {
      registerNow: 'Register Now',
      learnMore: 'Learn More',
    },
    about: {
      sectionLabel: 'About CEC',
      title: 'Where Engineering Meets ',
      titleHighlight: 'Identity',
      intro: "CEC grew out of the questions we ask once class is over and you are trying to figure out why you do this first of all. It is a space where you will not only see how things work, but why we build them.",
      ourStory: 'Our Story',
      storyP1: "We're a group of students who spend all our time learning circuits, logic, assembly, architecture, but still don't really know what kind of person actually uses all this stuff together. By fourth year, we know what we do but not who we are. First years are asking \"should I switch to CS?\" Fourth years are asking \"what even is computer engineering?\"",
      storyP2: "40-60% of engineering students drop out because of burnout and not seeing where this is going. CEC is our answer to that. It's where engineers share the messy reality. Where you hear about failure and leave seeing your struggles differently.",
      values: [
        {
          title: 'Why Failure Is Necessary',
          description: 'Learn how struggling now shapes the engineer you become later.',
        },
        {
          title: 'Why You Should Write Bad Code',
          description: 'Understand why messy first attempts beat perfect paralysis every time.',
        },
        {
          title: 'Why Solutions Start On Paper',
          description: 'Discover why the best code begins before you ever open your IDE.',
        },
      ],
    },
    event: {
      sectionLabel: 'The Event',
      title: 'One Day. ',
      titleHighlight: 'Lasting Impact.',
      intro: "CEC is a space where engineers talk openly about how they got here and what shaped them along the way. You will hear stories about failure, uncertainty, and slow progress, and how those experiences changed how people think about their work.",
      detailLabels: { date: 'Date', time: 'Time', venue: 'Venue' },
      whatYouExperience: "What You'll Experience",
      scheduleP1: 'The full schedule is still coming together.',
      scheduleP2: 'Expect short talks, shared meals, and time to actually sit with ideas and talk to people who are asking similar questions.',
      scheduleP3: "We're being intentional about leaving space for conversation, reflection, and the kinds of moments that don't fit neatly into a timetable.",
      scheduleP4: 'More details soon.',
      testimonialQuote: "Computer science is no more about computers than astronomy is about telescopes.",
      testimonialAttribution: 'Edsger Dijkstra',
      faqHeading: 'Frequently Asked Questions',
      reserveSpot: 'Reserve Your Spot',
    },
    speakers: {
      sectionLabel: 'Speakers',
      title: 'Voices That ',
      titleHighlight: 'Resonate',
      intro: "Our speakers are engineers, researchers, and builders who have been exactly where you are. People who have questioned their path, survived burnout, and figured out what actually matters. Their stories will show you that what you're going through right now isn't a problem. It's where your story begins.",
      applyHeadline: 'Have a story to share, or know someone who does?',
      applySubtext: "We're looking for voices across engineering, research, industry, and community. One of them might be you.",
      applyButton: 'Apply to Speak',
      applyDeadline: 'Applications close February 10, 2026.',
      applyFollowUp: 'Selected speakers will be contacted after the application review.',
      themes: ['Systems Thinking', 'Career Paths', 'Open Source', 'Hardware', 'Ethics', 'Community'],
    },
    team: {
      sectionLabel: 'The Team',
      title: 'Built By ',
      titleHighlight: 'Students',
      intro: "CEC is organized entirely by students who believe in the power of community-driven learning. We're engineers, designers, and builders just like you.",
    },
    contact: {
      sectionLabel: 'Contact',
      title: "Let's ",
      titleHighlight: 'Connect',
      intro: "Have questions? Want to get involved? We'd love to hear from you. Drop us a line or follow along on social media.",
      sendMessage: 'Send us a message',
      name: 'Name',
      email: 'Email',
      message: 'Message',
      placeholders: {
        name: 'Your name',
        email: 'you@example.com',
        message: "What's on your mind?",
      },
      sendButton: 'Send Message',
      stayUpdated: 'Stay Updated',
      newsletterCopy: 'Get schedule announcements, speaker reveals, and event updates delivered to your inbox.',
      subscribe: 'Subscribe',
      subscribing: 'Subscribing…',
      followAlong: 'Follow Along',
      orEmailUs: 'Or email us directly at',
      toastOpenEmail: 'Opening your email client. Send the message to reach us.',
      toastNewsletter: "You're on the list! Watch your inbox for updates.",
      toastNewsletterError: 'Something went wrong. Please try again.',
    },
    footer: {
      tagline: 'Built by engineers, for engineers.',
      copyright: 'Computer Engineering Conference',
    },
    notFound: {
      title: '404',
      description: 'Oops! Page not found',
      returnHome: 'Return to Home',
    },
    meta: {
      title: "CEC '26 — Computer Engineering Conference",
      description: 'A student-driven, TED-style conference connecting computer engineering skills to identity, meaning, and real-world impact. Spring 2026.',
      keywords: 'computer engineering, conference, students, tech, systems thinking, engineering identity',
      ogTitle: "CEC '26 — Computer Engineering Conference",
      ogDescription: 'A student-driven gathering where identity meets systems. Real engineering. Real stories. Real impact.',
    },
  },
};
