import type { Content } from './types';

export const contentFr: Content = {
  event: {
    date: '28 mars 2026',
    time: '14 h – 18 h',
    venue: "Université d'Ottawa",
    ctaSubtext: 'Places limitées • Inscription recommandée tôt',
  },
  links: {
    registration: 'https://luma.com/aoycaats',
    email: 'fabdo006@uottawa.ca',
    speakerApplication: 'https://forms.gle/sDqad7jwHUjBpk5KA',
    newsletterFormEndpoint: 'https://formspree.io/f/xdadvrog',
    instagram: {
      url: 'https://www.instagram.com/cegsc.ieee.uottawa/',
      handle: '@cegsc.ieee.uottawa',
    },
    linkedin: {
      url: 'https://www.linkedin.com/in/cegsc-ieee-uottawa-25879139b/',
      handle: 'CEGSC.IEEE. UOTTAWA',
    },
  },
  hero: {
    tagline: 'Printemps 2026 • Inscriptions ouvertes',
    title: {
      line1: 'Conférence',
      line2: 'en génie',
      line3: 'informatique',
    },
    subtitle: "Pour les ingénieurs qui savent ce qu'ils font, mais pas qui ils sont.\nVrais récits. Vrai impact.",
  },
  speakers: [
    { name: 'Wassim El Ahmar', role: 'Apprentissage automatique et vision par ordinateur', talkTitle: 'L\'avenir de l\'ingénieur à l\'ère de l\'IA', preview: 'Professeur à l\'Université d\'Ottawa. Doctorat en génie électrique et informatique, recherche à CVPR et ECCV.', detailType: 'quote' as const, detailText: 'I serve as a professor at the University of Ottawa in a long-term appointment (LTA), teaching courses ranging from programming and data structures to software engineering and interaction design. I have presented my academic research at top venues, such as CVPR and ECCV, advancing thermal-RGB sensor fusion, object detection and thermal multiple object tracking. I hold a PhD in electrical and computer engineering from the University of Ottawa, where my doctoral work focused on thermal-RGB sensory data for robust perception. I am also a licensed professional engineer (PEng) in Ontario.', attribution: 'Wassim El Ahmar', linkedin: 'https://www.linkedin.com/in/wassimea/', anchorId: 'speaker-wassim', image: '/speakers/wassim-el-ahmar.jpeg' },
    { name: 'Peter Oliha', role: 'Lead Backend Engineer | Fondateur SaaS • APIs et Cloud', talkTitle: 'De l\'optimisation au choix', preview: 'Ingénieur logiciel à Ottawa. 20 ans de code, 15 en professionnel. Construit des systèmes backend et un portfolio de produits.', detailType: 'quote' as const, detailText: 'I\'m a software engineer based in Ottawa, Canada. I\'ve been writing code for 20 years, 15 of those professionally. By day, I build backend systems and APIs. On the side, I\'m building a portfolio of products: Jobven, MapleStack, FindChildcare, and KidzLog. Most of what I know came from shipping my own projects.', attribution: 'Peter Oliha', linkedin: 'https://www.linkedin.com/in/peter-o-oliha-93b27118b/', anchorId: 'speaker-peter', image: '/speakers/peter-oliha.png' },
    { name: 'Jude Bennett', role: 'Développement logiciel', talkTitle: 'Coder les cieux', preview: 'Diplômé récent en génie informatique de Waterloo, développeur à NAV CANADA. Parcours de l\'université au trafic aérien canadien.', detailType: 'quote' as const, detailText: 'I\'m a recent graduate from the University of Waterloo\'s computer engineering program, and I currently work as a software developer for NAV CANADA here in Ottawa. My talk focuses on my journey from engineering undergraduate to full-time professional at one of the most important and least known companies in the country. When was the last time you flew on a plane? Did you think about who helps make sure it takes off, lands, and crosses the country without the sky turning into a giant scheduling disaster? Probably not. Most people do not. But behind every flight is a massive system of coordination, control, and technology that keeps Canadian air traffic moving safely and efficiently. One of the key organizations behind that system is NAV CANADA, one of the least talked about but most important companies in the country. Through my perspective, you\'ll get a look inside that world and what it\'s like to work at a company that keeps the whole country moving.', attribution: 'Jude Bennett', anchorId: 'speaker-jude', image: '/speakers/jude-bennett.jpg' },
    { name: 'Yousef Rafique', role: 'Ingénierie conseil - Automatisation et IA', talkTitle: 'Construire avec intention : pour qui construisons-nous vraiment?', preview: 'Ingénieur en informatique : startups, recherche, doctorat. Soutient maintenant l\'automatisation et l\'IA dans les grands réseaux.', detailType: 'quote' as const, detailText: 'I\'m a computer engineer who has moved across different parts of the field. I started by building a startup, then went into research and began a PhD focused on optimizing distributed cloud and IoT systems. I\'ve worked in R&D environments delivering new features, and today I work closer to customers, supporting automation and AI solutions in large network systems.', attribution: 'Yousef Rafique', linkedin: 'https://www.linkedin.com/in/yousefrafique/', anchorId: 'speaker-yousef', image: '/speakers/yousef-rafique.png' },
    { name: 'Alfredo Herrera', role: 'Consultant en circuits intégrés numériques', talkTitle: 'Sur le vérificateur accidentel', preview: 'Consultant en vérification ASIC/FPGA. 30+ ans chez Nortel, Ericsson, IBM, Ciena, Xilinx, AMD et autres.', detailType: 'quote' as const, detailText: 'I\'m a consultant on digital integrated circuit (ASIC, FPGA) verification and design. I have over 30 years of experience that includes work at Nortel, Ericsson, IBM, Ciena, Xilinx, AMD, ASML, MDA as well as some startups (Promatory, Axiado) and medium sized companies (Memotec, Dataradio). I have also volunteered for the IEEE and OIQ, coached house league baseball and soccer, and served as a councillor at summer camp. I live in Ottawa with my wife and three daughters.', attribution: 'Alfredo Herrera', linkedin: 'https://www.linkedin.com/in/alfredoherreraeng/', anchorId: 'speaker-alfredo', image: '/speakers/alfredo-herrera.jpeg' },
    { name: 'Matthew Jerabek', role: 'Gestion de l\'innovation et de l\'entrepreneuriat', talkTitle: 'Sur l\'ÉCHEC', preview: 'Créateur dans l\'âme. Dirige le makerspace à Oakland College. 10+ ans en marketing, a construit et échoué à bien des choses.', detailType: 'quote' as const, detailText: 'I\'m a maker at heart. I make physical things and digital things. I love to see where art and code can intersect, and I love novel ideas. I\'ve led a makerspace and opened it at Oakland College since 2018. I\'ve also been a marketing manager for many years with over 10 years of experience, and I\'ve built, tried, and failed at many different things along the way.', attribution: 'Matthew Jerabek', linkedin: 'https://www.linkedin.com/in/matthewjerabek/', anchorId: 'speaker-jerabek', image: '/speakers/matthew-jerabek.png' },
    { name: 'Stephen Gagné', role: 'Aider les entrepreneurs étudiants à transformer des idées audacieuses en résultats.', talkTitle: 'Écrire du code est la dernière chose que vous devriez faire', preview: 'Premier code à six ans en 1993. Pivot vers les sciences sociales et le commerce. Aide maintenant les entrepreneurs au Collège Algonquin.', detailType: 'quote' as const, detailText: 'I first discovered programming in 1993, at the age of six years old, when I took out a book of code from my local library. Although all I had at my disposal was a Q BASIC editor I had to launch from DOS, I was instantly hooked by what seemed like magic. I could type weird looking words into an editor, hit \'Run\' and see the computer come to life. In the 3 decades since that first experience, my relationship with programming hasn\'t been as consistent as I might like. A serious allergy to Integral Calculus cut short my dreams of being an engineer, and I took an educational detour into Social Sciences before pivoting completely into business. At 30, after realizing that my path wasn\'t leading me where I wanted to be, I went back to school to study Interactive Media Design. Coding came pretty naturally back to me, but it was completely different now. It no longer mattered how few lines I could do something in or how many milliseconds I could shave off the compute time. Instead, I had to learn to think about what my user wanted and how code might deliver that. Now, almost 33 years after I wrote my first ever lines of code, I work with dozens of aspiring tech entrepreneurs each year at Algonquin College, helping them learn to see code as a tool they can use to help their customers.', attribution: 'Stephen Gagné', linkedin: 'https://www.linkedin.com/in/stephengagne/', anchorId: 'speaker-stephen', image: '/speakers/stephen-gagne.png' },
    { name: 'Dan Cooper', role: 'Architecte TI en chef, Gouvernement du Canada', talkTitle: 'Sur l\'architecture de systèmes à l\'échelle gouvernementale et ce que signifie construire des technologies à l\'échelle nationale', preview: 'Architecte TI en chef au Bureau du dirigeant principal de l\'information du Canada. Conçoit des technologies à l\'échelle des systèmes nationaux.', detailType: 'description' as const, detailText: 'Dan Cooper serves as Chief IT Architect in the Office of the Chief Information Officer of Canada. His work offers a view into what it means to design and think about technology at the scale of national systems and public infrastructure.', linkedin: 'https://www.linkedin.com/in/thedancooper/', anchorId: 'speaker-dan', image: '/speakers/dan-cooper.png' },
  ],
  schedule: {
    sectionLabel: 'HORAIRE',
    title: 'Déroulement',
    intro: 'Trois blocs thématiques de récits, de leçons et de perspectives en génie — conçus pour passer des fondations à la réflexion, puis à l\'impact à grande échelle.',
    note: 'Les détails et biographies complètes des conférenciers sont dans la section Conférenciers.',
    blocks: [
      {
        blockLabel: 'BLOC 01',
        blockTitle: 'Fondations et premiers principes',
        type: 'speakers',
        items: [
          { name: 'Stephen Gagné', title: 'Écrire du code est la dernière chose que vous devriez faire', href: '#speaker-stephen' },
          { name: 'Alfredo Herrera', title: 'Sur le vérificateur accidentel', href: '#speaker-alfredo' },
          { name: 'Jude Bennett', title: 'Coder les cieux', href: '#speaker-jude' },
          { name: 'Wassim El Ahmar', title: 'L\'avenir de l\'ingénieur à l\'ère de l\'IA', href: '#speaker-wassim' },
        ],
      },
      {
        blockLabel: 'PAUSE 01',
        blockTitle: 'Courte pause',
        type: 'intermission',
      },
      {
        blockLabel: 'BLOC 02',
        blockTitle: 'Réflexion et perspective',
        type: 'speakers',
        items: [
          { name: 'Matt Lemay', title: "L'avantage de l'ingénieur : construire une IA fiable par les normes et l'architecture" },
          { name: 'Peter Oliha', title: 'De l\'optimisation au choix', href: '#speaker-peter' },
          { name: 'Michel de Léséleuc', title: 'Du laboratoire au leadership : 40 ans en RF' },
        ],
      },
      {
        blockLabel: 'PAUSE 02',
        blockTitle: 'Longue pause',
        type: 'intermission',
      },
      {
        blockLabel: 'BLOC 03',
        blockTitle: 'Échelle et impact',
        type: 'speakers',
        items: [
          { name: 'Yousef Rafique', title: 'Construire avec intention : pour qui construisons-nous vraiment?', href: '#speaker-yousef' },
          { name: 'Matthew Jerabek', title: 'Sur l\'ÉCHEC', href: '#speaker-jerabek' },
          { name: 'Dan Cooper', title: 'Sur l\'architecture de systèmes à l\'échelle gouvernementale', href: '#speaker-dan' },
        ],
      },
      {
        blockLabel: 'PAUSE 03',
        blockTitle: 'Dîner et réseautage',
        type: 'intermission',
      },
    ],
  },
  team: [
    { name: 'Mariia Yermolenko', role: 'Organisatrice principale', image: '/team/mariia.jpg' },
    { name: 'Fatimata Abdou Dramane', role: 'Directrice de programme', image: '/team/fatima.jpg' },
    { name: 'Asif Rahman', role: 'Logistique', image: '/team/asif.jpg' },
    { name: 'Paul Chukwu', role: 'Commandites', image: '/team/paul.jpg' },
    { name: 'Basma Ben Taleb', role: 'Marketing', image: '/team/basma.jpg' },
    { name: 'Dounia Bouimajdil', role: 'Opérations et expérience', image: '/team/Dounia.jpg' },
  ],
  faqs: [
    {
      question: "Où aura lieu l'événement ?",
      answer: "L'événement se tiendra à l'uOttawa. Le lieu exact sera communiqué une fois finalisé.",
    },
    {
      question: 'Quand le programme sera-t-il publié ?',
      answer: "Nous publierons le programme complet plus près de l'événement, une fois les conférenciers confirmés.",
    },
    {
      question: "À qui s'adresse cet événement ?",
      answer: "À toute personne en tech ou en génie qui s'est déjà sentie incertaine sur son parcours, a questionné sa direction ou voulu une vision plus claire de ce que signifie vraiment construire des choses. Étudiants, diplômés récents et professionnels sont les bienvenus.",
    },
    {
      question: "Puis-je participer comme conférencier ou bénévole ?",
      answer: "Oui. Nous accueillons encore des propositions de conférenciers et des bénévoles. Plus d'infos sur le site ; n'hésitez pas à nous contacter si vous ne savez pas où vous placer.",
    },
    {
      question: 'Y aura-t-il de la nourriture ?',
      answer: "Oui. Nous prévoyons un repas partagé pendant l'événement ; les détails suivront.",
    },
    {
      question: 'Que dois-je apporter ?',
      answer: "Juste vous-même et l'esprit ouvert. Aucune préparation requise.",
    },
  ],
  ui: {
    nav: {
      schedule: 'Horaire',
      about: 'À propos',
      speakers: 'Conférenciers',
      event: 'Événement',
      team: 'Équipe',
      contact: 'Contact',
      attend: 'Participer',
    },
    hero: {
      registerNow: 'S\'inscrire',
      learnMore: 'En savoir plus',
    },
    about: {
      sectionLabel: 'À propos du CEC',
      title: 'Où le génie rencontre l\'',
      titleHighlight: 'identité',
      intro: "Le CEC est né des questions qu'on se pose une fois les cours terminés, quand on essaie de comprendre pourquoi on fait tout ça. C'est un espace où l'on voit non seulement comment les choses fonctionnent, mais pourquoi on les construit.",
      ourStory: 'Notre histoire',
      storyP1: "Nous sommes un groupe d'étudiants qui passons notre temps à apprendre les circuits, la logique, l'assembleur, l'architecture, sans vraiment savoir quel genre de personne utilise tout ça. En quatrième année, on sait ce qu'on fait mais pas qui on est. Les premières années se demandent « est-ce que je devrais passer en informatique ? » Les quatrièmes : « c'est quoi au juste le génie informatique ? »",
      storyP2: "40 à 60 % des étudiants en génie abandonnent à cause du burnout et du flou sur la suite. Le CEC est notre réponse. C'est là que les ingénieurs partagent la réalité désordonnée. Où l'on parle d'échec et d'où l'on repart en voyant ses difficultés autrement.",
      values: [
        {
          title: 'Pourquoi l\'échec est nécessaire',
          description: 'Comprendre comment les difficultés d\'aujourd\'hui forgent l\'ingénieur de demain.',
        },
        {
          title: 'Pourquoi écrire du mauvais code',
          description: 'Comprendre pourquoi des premiers essais désordonnés battent la paralysie parfaite.',
        },
        {
          title: 'Pourquoi les solutions commencent sur le papier',
          description: 'Découvrir pourquoi le meilleur code commence avant d\'ouvrir l\'IDE.',
        },
      ],
    },
    event: {
      sectionLabel: "L'événement",
      title: 'Un jour. ',
      titleHighlight: 'Un impact durable.',
      intro: "Le CEC est un espace où les ingénieurs parlent ouvertement de comment ils en sont arrivés là et de ce qui les a façonnés. Vous entendrez des récits d'échec, d'incertitude et de progrès lent, et comment ces expériences ont changé la façon dont les gens voient leur travail.",
      detailLabels: { date: 'Date', time: 'Heure', venue: 'Lieu' },
      whatYouExperience: "Ce que vous vivrez",
      scheduleP1: 'Le programme complet se précise.',
      scheduleP2: 'Prévoyez des conférences courtes, des repas partagés et du temps pour digérer les idées et échanger avec des gens qui se posent les mêmes questions.',
      scheduleP3: "Nous voulons laisser de la place à la conversation, à la réflexion et aux moments qui ne rentrent pas dans un emploi du temps.",
      scheduleP4: 'Plus de détails bientôt.',
      testimonialQuote: "L'informatique n'a pas plus à voir avec les ordinateurs que l'astronomie avec les télescopes.",
      testimonialAttribution: 'Edsger Dijkstra',
      faqHeading: 'Questions fréquentes',
      reserveSpot: 'Réserver ma place',
    },
    speakers: {
      sectionLabel: 'Conférenciers',
      title: 'Des voix qui ',
      titleHighlight: 'résonnent',
      intro: "Nos conférenciers sont des ingénieurs, chercheurs et bâtisseurs qui ont été exactement où vous êtes. Des gens qui ont questionné leur parcours, traversé le burnout et compris ce qui compte vraiment. Leurs récits montrent que ce que vous vivez n'est pas un problème. C'est le début de votre histoire.",
      applyHeadline: 'Une histoire à partager, ou quelqu\'un qui en a une ?',
      applySubtext: 'Nous cherchons des voix en ingénierie, recherche, industrie et communauté. L\'une d\'elles pourrait être la vôtre.',
      applyButton: 'Postuler comme conférencier',
      applyDeadline: 'Les candidatures se terminent le 10 février 2026.',
      applyFollowUp: 'Les conférenciers retenus seront contactés après l\'examen des candidatures.',
      themes: ['Pensée système', 'Parcours professionnels', 'Open source', 'Matériel', 'Éthique', 'Communauté'],
    },
    team: {
      sectionLabel: "L'équipe",
      title: 'Construit par des ',
      titleHighlight: 'étudiants',
      intro: "Le CEC est organisé entièrement par des étudiants qui croient au pouvoir de l'apprentissage par la communauté. Nous sommes ingénieurs, designers et bâtisseurs comme vous.",
    },
    contact: {
      sectionLabel: 'Contact',
      title: 'Restons ',
      titleHighlight: 'en contact',
      intro: "Des questions ? Envie de vous impliquer ? Nous aimerions avoir de vos nouvelles. Écrivez-nous ou suivez-nous sur les réseaux.",
      sendMessage: 'Nous envoyer un message',
      name: 'Nom',
      email: 'Courriel',
      message: 'Message',
      placeholders: {
        name: 'Votre nom',
        email: 'vous@exemple.com',
        message: "Qu'avez-vous en tête ?",
      },
      sendButton: 'Envoyer',
      stayUpdated: 'Restez informés',
      newsletterCopy: 'Recevez les annonces, les conférenciers et les mises à jour par courriel.',
      subscribe: 'S\'abonner',
      subscribing: 'Inscription…',
      followAlong: 'Nous suivre',
      orEmailUs: 'Ou écrivez-nous directement à',
      toastOpenEmail: 'Ouverture de votre messagerie. Envoyez le message pour nous joindre.',
      toastNewsletter: "Vous êtes inscrit ! Surveillez votre boîte de réception.",
      toastNewsletterError: 'Une erreur s\'est produite. Veuillez réessayer.',
    },
    footer: {
      tagline: 'Par des ingénieurs, pour des ingénieurs.',
      copyright: 'Conférence en génie informatique',
    },
    notFound: {
      title: '404',
      description: 'Oups ! Page introuvable',
      returnHome: 'Retour à l\'accueil',
    },
    meta: {
      title: "CEC '26 — Conférence en génie informatique",
      description: "Une conférence style TED, portée par des étudiants, qui relie les compétences en génie informatique à l'identité, au sens et à l'impact réel. Printemps 2026.",
      keywords: 'génie informatique, conférence, étudiants, tech, pensée système, identité ingénieur',
      ogTitle: "CEC '26 — Conférence en génie informatique",
      ogDescription: "Un rassemblement porté par des étudiants où l'identité rencontre les systèmes. Vrai génie. Vrais récits. Vrai impact.",
    },
  },
};
